@startuml LL Abdul website

interface Resource {
    name: string
    icon: URL
    description: string
}

interface Champion extends Resource {
    alias : string
}

interface MatchupGuide {
    early: string
    mid: string
    videos: URL[]
    difficulty:  MatchupDifficulty
    runes: Runes
    startItems : Item[]
    build : Item[]
    champion: Champion
    enemyChampion : Champion
    summonerSpells : SummonerSpell[]
}

MatchupGuide -up-> "2" Champion: currentChamp and enemyChamp
MatchupGuide -> "*" Item: startItems AND build
MatchupGuide -down-> "2" SummonerSpell: summonerSpells
MatchupGuide -left-> "1" Runes: runePage
MatchupGuide -down-> "1" MatchupDifficulty: difficulty

interface Runes {
    primary: string
    secondary: string
    shards: string[]  //shard names "adaptive force", "adaptive force", "health"
}

interface SummonerSpell extends Resource {
    cooldown: number
} 

interface Item extends Resource {
    cost: number
}

enum MatchupDifficulty {
    EASY = "EASY",
    SKILL = "SKILL",
    HARD = "HARD"
}

interface ChampionGuide{
    champion : Champion
    early : string
    mid : string
    late : string
    videos: URL[]
}

enum MechanicsDifficulty {
    BASIC = "BASIC",
    ADVANCED = "ADVANCED",
    EXPERT = "EXPERT"
}

interface MechanicsGuide{
    champion : Champion
    videos : URL[]
    description : string
    difficulty : MechanicsDifficulty
}

ChampionGuide -up-> "*" MechanicsGuide: mechanics guides
MechanicsGuide -down-> "1" MechanicsDifficulty: difficulty



